Repository adaptlearning/adapt-contrib-tutor, pull requests merged in 2022-08, with the labels that each got.

#76 Fix: replace deprecated a11y_attrs_heading usage (refs #67)
  js/TutorModel.js
  templates/tutor.hbs
Labels: bug, accessibility

#78 Fix: Stop _id property from directly rendering the _id view
  js/TutorModel.js
Labels: bug

#75 Update: Add accessible title (refs #74)
  js/TutorModel.js
  templates/tutor.hbs
Labels: enhancement, accessibility
